# Generated by Django 5.2.4 on 2025-08-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_alter_patient_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="avatar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("M", "MALE"), ("F", "FEMALE"), ("O", "OTHER")], max_length=20
            ),
        ),
    ]
