# Generated by Django 5.2.4 on 2025-07-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("S", "SYSTEM"),
                    ("B", "BILL"),
                    ("A", "APPOINTMENT"),
                    ("F", "FOLLOWUP"),
                    ("O", "OTHER"),
                ],
                max_length=2,
            ),
        ),
    ]
