# Generated by Django 5.2.4 on 2025-07-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
