# Generated by Django 5.2.4 on 2025-07-29 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("service_name", models.CharField(max_length=100)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("T", "TEST"),
                            ("I", "IMAGING"),
                            ("C", "CONSULTATION"),
                            ("O", "OTHER"),
                        ],
                        max_length=1,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("symptoms", models.TextField()),
                ("number", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "PENDING"),
                            ("C", "CONFIRMED"),
                            ("X", "CANCELLED"),
                            ("D", "COMPLETED"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="doctors.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="patients.patient",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="doctors.schedule",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AppointmentNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "noteType",
                    models.CharField(
                        choices=[("D", "DOCTOR"), ("P", "PATIENT")], max_length=1
                    ),
                ),
                ("noteText", models.TextField()),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("O", "ORDERED"), ("C", "COMPLETED")], max_length=1
                    ),
                ),
                ("result", models.TextField(blank=True, null=True)),
                ("number", models.IntegerField(blank=True, null=True)),
                ("order_time", models.DateTimeField(blank=True, null=True)),
                ("result_time", models.DateTimeField(blank=True, null=True)),
                (
                    "result_file_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "result_file_public_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="appointments.appointment",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="doctors.examinationroom",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="appointments.service",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
