# Generated by Django 5.2.4 on 2025-07-30 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentnote',
            old_name='noteText',
            new_name='note_text',
        ),
        migrations.RenameField(
            model_name='appointmentnote',
            old_name='noteType',
            new_name='note_type',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='number',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='appointmentnote',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentnote',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appointment_notes', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='service_orders', to='appointments.service'),
        ),
    ]
