# Generated by Django 5.2.4 on 2025-07-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "PENDING"),
                    ("C", "CONFIRMED"),
                    ("X", "CANCELLED"),
                    ("D", "COMPLETED"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="appointmentnote",
            name="noteType",
            field=models.CharField(
                choices=[("D", "DOCTOR"), ("P", "PATIENT")], max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("T", "TEST"),
                    ("I", "IMAGING"),
                    ("C", "CONSULTATION"),
                    ("O", "OTHER"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="status",
            field=models.CharField(
                choices=[("O", "ORDERED"), ("C", "COMPLETED")], max_length=2
            ),
        ),
    ]
