# Generated by Django 5.2.4 on 2025-07-31 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_alter_appointment_status_and_more"),
        ("appointments", "0002_rename_notetext_appointmentnote_note_text_and_more"),
    ]

    operations = []
