# Generated by Django 5.2.4 on 2025-08-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_merge_20250801_0737"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointmentnote",
            name="noteType",
        ),
        migrations.AlterField(
            model_name="appointmentnote",
            name="note_type",
            field=models.CharField(
                choices=[("D", "DOCTOR"), ("P", "PATIENT")], max_length=2
            ),
        ),
    ]
