# Generated by Django 5.2.4 on 2025-08-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_remove_appointmentnote_notetype_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointmentnote",
            name="noteType",
        ),
    ]
