# Generated by Django 5.2.4 on 2025-08-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0006_alter_appointment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="symptoms",
            field=models.TextField(blank=True, null=True),
        ),
    ]
