# Generated by Django 5.2.4 on 2025-07-29 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("department_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("identity_number", models.CharField(max_length=20, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birthday", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "MALE"), ("F", "FEMALE"), ("O", "OTHER")],
                        max_length=1,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "academic_degree",
                    models.CharField(
                        choices=[
                            ("B", "BS"),
                            ("C1", "BS_CKI"),
                            ("C2", "BS_CKII"),
                            ("T1", "ThS_BS"),
                            ("T2", "TS_BS"),
                            ("P1", "PGS_TS_BS"),
                            ("G1", "GS_TS_BS"),
                        ],
                        max_length=10,
                    ),
                ),
                ("specialization", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("E", "EXAMINATION"), ("S", "SERVICE")], max_length=1
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="doctors.department",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="users.user"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExaminationRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("E", "EXAMINATION"), ("T", "TEST")], max_length=1
                    ),
                ),
                ("building", models.CharField(max_length=20)),
                ("floor", models.IntegerField()),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="doctors.department",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("work_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("M", "MORNING"),
                            ("A", "AFTERNOON"),
                            ("E", "EVENING"),
                            ("N", "NIGHT"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="doctors.doctor",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="doctors.examinationroom",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
