# Generated by Django 5.2.4 on 2025-07-30 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="last_name",
        ),
        migrations.AddField(
            model_name="department",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="founded_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="head_doctor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="avatar",
            field=models.CharField(
                default="https://cdn.kona-blue.com/upload/kona-blue_com/post/images/2024/09/19/465/avatar-trang-1.jpg",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="consultation_fee",
            field=models.DecimalField(decimal_places=2, default=200000, max_digits=10),
        ),
        migrations.AddField(
            model_name="doctor",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="examinationroom",
            name="room_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="academic_degree",
            field=models.CharField(
                choices=[
                    ("B", "BS"),
                    ("C1", "BS_CKI"),
                    ("C2", "BS_CKII"),
                    ("T1", "ThS_BS"),
                    ("T2", "TS_BS"),
                    ("P1", "PGS_TS_BS"),
                    ("G1", "GS_TS_BS"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="gender",
            field=models.CharField(
                choices=[("M", "MALE"), ("F", "FEMALE"), ("O", "OTHER")], max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="type",
            field=models.CharField(
                choices=[("E", "EXAMINATION"), ("S", "SERVICE")], max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT, to="users.user"
            ),
        ),
        migrations.AlterField(
            model_name="examinationroom",
            name="building",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="examinationroom",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="doctors.department",
            ),
        ),
        migrations.AlterField(
            model_name="examinationroom",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="examinationroom",
            name="type",
            field=models.CharField(
                choices=[("E", "EXAMINATION"), ("T", "TEST")], max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="shift",
            field=models.CharField(
                choices=[("MORNING", "Morning"), ("AFTERNOON", "Afternoon")],
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
