# Generated by Django 5.2.4 on 2025-07-30 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_remove_doctor_last_name_department_email_and_more"),
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="email",
        ),
        migrations.RemoveField(
            model_name="department",
            name="founded_year",
        ),
        migrations.RemoveField(
            model_name="department",
            name="head_doctor_id",
        ),
        migrations.RemoveField(
            model_name="department",
            name="location",
        ),
        migrations.RemoveField(
            model_name="department",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="consultation_fee",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="examinationroom",
            name="room_name",
        ),
        migrations.AddField(
            model_name="doctor",
            name="last_name",
            field=models.CharField(default=".Jr", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="doctor",
            name="academic_degree",
            field=models.CharField(
                choices=[
                    ("B", "BS"),
                    ("C1", "BS_CKI"),
                    ("C2", "BS_CKII"),
                    ("T1", "ThS_BS"),
                    ("T2", "TS_BS"),
                    ("P1", "PGS_TS_BS"),
                    ("G1", "GS_TS_BS"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="users.user"
            ),
        ),
        migrations.AlterField(
            model_name="examinationroom",
            name="building",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="examinationroom",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="doctors.department"
            ),
        ),
        migrations.AlterField(
            model_name="examinationroom",
            name="note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="shift",
            field=models.CharField(
                choices=[
                    ("M", "MORNING"),
                    ("A", "AFTERNOON"),
                    ("E", "EVENING"),
                    ("N", "NIGHT"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
