# Generated by Django 5.2.4 on 2025-08-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_remove_department_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="avatar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
