# Generated by Django 5.2.4 on 2025-08-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0004_doctor_avatar_doctor_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="current_patients",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="schedule",
            name="default_appointment_duration_minutes",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="schedule",
            name="max_patients",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="schedule",
            name="status",
            field=models.CharField(
                choices=[("AVAILABLE", "Available"), ("FULL", "Full")],
                default="AVAILABLE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="gender",
            field=models.CharField(
                choices=[("M", "MALE"), ("F", "FEMALE"), ("O", "OTHER")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="type",
            field=models.CharField(
                choices=[("E", "EXAMINATION"), ("S", "SERVICE")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="examinationroom",
            name="type",
            field=models.CharField(
                choices=[("E", "EXAMINATION"), ("T", "TEST")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="shift",
            field=models.CharField(
                choices=[
                    ("M", "MORNING"),
                    ("A", "AFTERNOON"),
                    ("E", "EVENING"),
                    ("N", "NIGHT"),
                ],
                max_length=20,
            ),
        ),
    ]
