# Generated by Django 5.2.4 on 2025-08-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0005_schedule_current_patients_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="avatar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
