# Generated by Django 5.2.4 on 2025-08-01 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0002_alter_bill_status_alter_transaction_payment_method_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="billdetail",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="details",
                to="payments.bill",
            ),
        ),
    ]
