# Generated by Django 5.2.4 on 2025-08-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_billdetail_bill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="status",
            field=models.CharField(
                choices=[("P", "PAID"), ("U", "UNPAID")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[("C", "CASH"), ("B", "ONLINE_BANKING"), ("D", "CARD")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[("S", "SUCCESS"), ("F", "FAILED"), ("P", "PENDING")],
                max_length=20,
            ),
        ),
    ]
