# Generated by Django 5.2.4 on 2025-08-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0004_alter_bill_status_alter_transaction_payment_method_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="status",
            field=models.CharField(
                choices=[("P", "PAID"), ("B", "BOOKING_PAID"), ("U", "UNPAID")],
                max_length=20,
            ),
        ),
    ]
