# Generated by Django 5.2.4 on 2025-07-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("A", "ADMIN"), ("D", "DOCTOR"), ("P", "PATIENT")],
                max_length=2,
            ),
        ),
    ]
