# Generated by Django 5.2.4 on 2025-08-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_deleted_at_user_is_active_user_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("A", "ADMIN"), ("D", "DOCTOR"), ("P", "PATIENT")],
                default="P",
                max_length=20,
            ),
        ),
    ]
