# Generated by Django 5.2.4 on 2025-07-29 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("medicine_name", models.CharField(max_length=100)),
                ("manufactor", models.CharField(blank=True, max_length=100, null=True)),
                ("category", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("usage", models.TextField()),
                ("unit", models.CharField(max_length=50)),
                ("is_insurance_covered", models.BooleanField(default=False)),
                (
                    "insurance_discount_percent",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "insurance_discount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("side_effects", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.IntegerField()),
                ("avatar", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("is_follow_up", models.BooleanField(default=False)),
                ("diagnosis", models.TextField()),
                ("systolic_blood_pressure", models.IntegerField(blank=True, null=True)),
                (
                    "diastolic_blood_pressure",
                    models.IntegerField(blank=True, null=True),
                ),
                ("heart_rate", models.IntegerField(blank=True, null=True)),
                ("blood_sugar", models.IntegerField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="appointments.appointment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PrescriptionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dosage", models.CharField(max_length=100)),
                ("frequency", models.CharField(max_length=50)),
                ("duration", models.CharField(max_length=50)),
                ("quantity", models.IntegerField()),
                ("prescription_notes", models.TextField(blank=True, null=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="pharmacy.medicine",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="pharmacy.prescription",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
