# Generated by Django 5.2.4 on 2025-08-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="avatar",
        ),
    ]
