# Generated by Django 5.2.4 on 2025-08-22 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0002_remove_medicine_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="prescriptiondetail",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="prescription_details",
                to="pharmacy.prescription",
            ),
        ),
    ]
