# Generated by Django 5.2.4 on 2025-08-26 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0007_appointment_note_alter_appointment_symptoms"),
        ("patients", "0003_patient_avatar_alter_patient_gender"),
        ("pharmacy", "0003_prescription_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="appointments.appointment",
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="prescription",
            constraint=models.UniqueConstraint(
                fields=("appointment",), name="unique_prescription_per_appointment"
            ),
        ),
    ]
